/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Errors503RouteImport } from './routes/errors/503'
import { Route as Errors500RouteImport } from './routes/errors/500'
import { Route as Errors404RouteImport } from './routes/errors/404'
import { Route as Errors403RouteImport } from './routes/errors/403'
import { Route as Errors401RouteImport } from './routes/errors/401'
import { Route as AuthValidateCodeRouteImport } from './routes/auth/validate-code'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppSettingsRouteRouteImport } from './routes/app/settings/route'
import { Route as AppSettingsSettingsRouteImport } from './routes/app/settings/settings'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppSettingsNotificationsRouteImport } from './routes/app/settings/notifications'
import { Route as AppSettingsAppearanceRouteImport } from './routes/app/settings/appearance'
import { Route as AppManagementCategoriesRouteImport } from './routes/app/management/categories'
import { Route as AppManagementAccountsRouteImport } from './routes/app/management/accounts'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors503Route = Errors503RouteImport.update({
  id: '/errors/503',
  path: '/errors/503',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors500Route = Errors500RouteImport.update({
  id: '/errors/500',
  path: '/errors/500',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors404Route = Errors404RouteImport.update({
  id: '/errors/404',
  path: '/errors/404',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors403Route = Errors403RouteImport.update({
  id: '/errors/403',
  path: '/errors/403',
  getParentRoute: () => rootRouteImport,
} as any)
const Errors401Route = Errors401RouteImport.update({
  id: '/errors/401',
  path: '/errors/401',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthValidateCodeRoute = AuthValidateCodeRouteImport.update({
  id: '/auth/validate-code',
  path: '/auth/validate-code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsSettingsRoute = AppSettingsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRouteRoute,
  } as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppManagementCategoriesRoute = AppManagementCategoriesRouteImport.update({
  id: '/management/categories',
  path: '/management/categories',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppManagementAccountsRoute = AppManagementAccountsRouteImport.update({
  id: '/management/accounts',
  path: '/management/accounts',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/validate-code': typeof AuthValidateCodeRoute
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/app/management/accounts': typeof AppManagementAccountsRoute
  '/app/management/categories': typeof AppManagementCategoriesRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/settings': typeof AppSettingsSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/validate-code': typeof AuthValidateCodeRoute
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/app/management/accounts': typeof AppManagementAccountsRoute
  '/app/management/categories': typeof AppManagementCategoriesRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/settings': typeof AppSettingsSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/validate-code': typeof AuthValidateCodeRoute
  '/errors/401': typeof Errors401Route
  '/errors/403': typeof Errors403Route
  '/errors/404': typeof Errors404Route
  '/errors/500': typeof Errors500Route
  '/errors/503': typeof Errors503Route
  '/app/management/accounts': typeof AppManagementAccountsRoute
  '/app/management/categories': typeof AppManagementCategoriesRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/settings': typeof AppSettingsSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/settings'
    | '/app/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/validate-code'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/errors/503'
    | '/app/management/accounts'
    | '/app/management/categories'
    | '/app/settings/appearance'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/settings'
    | '/app/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/validate-code'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/errors/503'
    | '/app/management/accounts'
    | '/app/management/categories'
    | '/app/settings/appearance'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/settings'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/settings'
    | '/app/dashboard'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/validate-code'
    | '/errors/401'
    | '/errors/403'
    | '/errors/404'
    | '/errors/500'
    | '/errors/503'
    | '/app/management/accounts'
    | '/app/management/categories'
    | '/app/settings/appearance'
    | '/app/settings/notifications'
    | '/app/settings/profile'
    | '/app/settings/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthValidateCodeRoute: typeof AuthValidateCodeRoute
  Errors401Route: typeof Errors401Route
  Errors403Route: typeof Errors403Route
  Errors404Route: typeof Errors404Route
  Errors500Route: typeof Errors500Route
  Errors503Route: typeof Errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/503': {
      id: '/errors/503'
      path: '/errors/503'
      fullPath: '/errors/503'
      preLoaderRoute: typeof Errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/500': {
      id: '/errors/500'
      path: '/errors/500'
      fullPath: '/errors/500'
      preLoaderRoute: typeof Errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/404': {
      id: '/errors/404'
      path: '/errors/404'
      fullPath: '/errors/404'
      preLoaderRoute: typeof Errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/403': {
      id: '/errors/403'
      path: '/errors/403'
      fullPath: '/errors/403'
      preLoaderRoute: typeof Errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/errors/401': {
      id: '/errors/401'
      path: '/errors/401'
      fullPath: '/errors/401'
      preLoaderRoute: typeof Errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/validate-code': {
      id: '/auth/validate-code'
      path: '/auth/validate-code'
      fullPath: '/auth/validate-code'
      preLoaderRoute: typeof AuthValidateCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings/settings': {
      id: '/app/settings/settings'
      path: '/settings'
      fullPath: '/app/settings/settings'
      preLoaderRoute: typeof AppSettingsSettingsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/notifications': {
      id: '/app/settings/notifications'
      path: '/notifications'
      fullPath: '/app/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/appearance': {
      id: '/app/settings/appearance'
      path: '/appearance'
      fullPath: '/app/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/management/categories': {
      id: '/app/management/categories'
      path: '/management/categories'
      fullPath: '/app/management/categories'
      preLoaderRoute: typeof AppManagementCategoriesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/management/accounts': {
      id: '/app/management/accounts'
      path: '/management/accounts'
      fullPath: '/app/management/accounts'
      preLoaderRoute: typeof AppManagementAccountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSettingsRoute: typeof AppSettingsSettingsRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSettingsRoute: AppSettingsSettingsRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppManagementAccountsRoute: typeof AppManagementAccountsRoute
  AppManagementCategoriesRoute: typeof AppManagementCategoriesRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppManagementAccountsRoute: AppManagementAccountsRoute,
  AppManagementCategoriesRoute: AppManagementCategoriesRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthValidateCodeRoute: AuthValidateCodeRoute,
  Errors401Route: Errors401Route,
  Errors403Route: Errors403Route,
  Errors404Route: Errors404Route,
  Errors500Route: Errors500Route,
  Errors503Route: Errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
